image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
  - name: Run
    command: dotnet run
  - name: postgres
    init: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev
    command: |
      export GITPOD_IP=$(curl ifconfig.me)
      source  "$THEIA_WORKSPACE_ROOT/backend-flask/bin/rds/update-sg-rule"

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - ckolkman.vscode-postgres
    - dsznajder.es7-react-js-snippets
    - formulahendry.auto-close-tag
    - mongodb.mongodb-vscode
    - ms-azuretools.vscode-docker
    - ms-dotnettools.vscode-dotnet-runtime
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - patcx.vscode-nuget-gallery
    - PKief.material-icon-theme
    - zxh404.vscode-proto3
